spring.application.name=FinanceModule
spring.datasource.url = jdbc:postgresql://localhost:5432/finance
spring.datasource.username = postgres
spring.datasource.password = Shreya@2025
spring.jpa.hibernate.ddl-auto=update
server.port=9090